[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Preprod: rama develop
[context.branch-deploy]
  command = "npm run build"

# Producción: rama main
[context.production]
  command = "npm run build"
